import { DefaultTheme } from "styled-components";

export const DarkMode: DefaultTheme = {
    bgColor         : "#2f3640",
    bgDarkColor     : "#1E242D",
    bgHeader        : "#1a202c",
    bgWhite         : "#fff",
    bgGray          : "#A0AEC0",
    lightGray       : "#f5f7fa",
    bgDark          : "rgba(0, 0, 0, 0.5)",
    txtColor        : "#f5f6fa",
    accentColor     : "#9c88ff",
    yellowColor     : "#facc15",
    cardBg          : "#1E242D",                 
    cardShadow      : "rgba(0, 0, 0, 0.3)",
    cardHoverShadow : "rgba(0, 0, 0, 0.5)",
    textPrimary     : "#f5f6fa",            
    textSecondary   : "#A0AEC0",          
    statusBorder    : "#9c88ff",          
    statusHoverBg   : "#9c88ff",
    statusHoverText : "#1E242D",        
    actionText      : "#A0AEC0",
    actionHoverText : "#f5f6fa",
    royalblue       : "royalblue",
    indianRed       : "#CD5C5C",  
}